### ISSUE TITLE
Wrong serie number?

### ISSUE THREAD

**Issue by ghost** [IIvec/Stockfish#1491]
Is CorChess 2 the correct serie number? On its relative non-embedded version it's written 1.4.

**Comment by IIvec** [comment]
CorChess 2 will be the only CorChess soon. The branch will be called only
corchess, but it will have an embedded net.
It will be appropriate only for long analysis as it'll be weaker on shorter
time controls.

Regards,
Ivan

pet, 13. kol 2021. 04:21 massimilianogoi ***@***.***> je
napisao:
